### ISSUE TITLE
I've got: [PDOException]  SQLSTATE[01002] Adaptive Server connection failed (severity 9)

### ISSUE THREAD

**Issue by rubenlb** [realestateconz/MssqlBundle#19]
everything works. 
I did:
tsql -H 192.168.0.4 -p 1433 -U username -P pword -D BDRrhh

locale is "LC_CTYPE=es_MX.UTF-8;LC_NUMERIC=es_BO.UTF-8;LC_TIME=es_BO.UTF-8;LC_COLLATE=es_MX.UTF-8;LC_MONETARY=es_BO.UTF-8;LC_MESSAGES=es_MX.UTF-8;LC_PAPER=es_BO.UTF-8;LC_NAME=es_BO.UTF-8;LC_ADDRESS=es_BO.UTF-8;LC_TELEPHONE=es_BO.UTF-8;LC_MEASUREMENT=es_BO.UTF-8;LC_IDENTIFICATION=es_BO.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Default database being set to BDRrhh

and i can do querys in php file with mssql_connect('192.168.0.4','username','pword);
but in symfony 2.3 i've got [PDOException]  SQLSTATE[01002] Adaptive Server connection failed (severity 9)

please help me.....

**Comment by rogeriolino** [comment]
**config.yml**:

```yml
# Doctrine Configuration
doctrine:
    dbal:
        driver_class:   \Realestate\MssqlBundle\Driver\PDODblib\Driver
        host:     "%database_host%"
        user:     "%database_user%"
        password: "%database_password%"
        options:
            charset: UTF-8
```
In ```%database_host%``` specify the freetds entry name.

Ex:

**freetds.conf**:

```
[databasehost_tds]
        host = 192.168.0.4
        port = 1433
        tds version = 8.0
        client charset = UTF-8
        text size = 20971520
```

**parameters.yml** or  **config_dev.yml** or **config_prod.yml**:

```yml
parameters:
    database_host: databasehost_tds
```
